/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dbcon.DB;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.file.Paths;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author User
 */
public class view extends javax.swing.JPanel {


    /**
     * Creates new form view
     */
     byte[] qrBytes;
     String studID;
public  view(String studID) {
    this.studID=studID;
    initComponents();

    try (Connection con = DB.getConnection();
         PreparedStatement preparedStatement = con.prepareStatement("SELECT firstName, middleName, lastName, extension, email, mobileNo, qr, addedby, dateAdded, timeAdded, rfid, img, yearlvl FROM students WHERE studentID = ?")) {
        preparedStatement.setString(1, studID);

        try (ResultSet resultSet = preparedStatement.executeQuery()) {
            if (resultSet.next()) {
                String firstName = resultSet.getString("firstName");
                String middleName = resultSet.getString("middleName");
                String lastName = resultSet.getString("lastName");
                String extension = resultSet.getString("extension");
                String email = resultSet.getString("email");
                String mobileNo = resultSet.getString("mobileNo");
                String addedby = resultSet.getString("addedby");
                String dateAdded = resultSet.getString("dateAdded");
                String timeAdded = resultSet.getString("timeAdded");
                // Corrected: Get image as a byte array
                byte[] imgBytes = resultSet.getBytes("img");
                // Corrected: Get year level
                
                
                String yrLevel = resultSet.getString("yearlvl");

                String fullName = firstName + " " + (middleName != null ? middleName + " " : "") + lastName + " " + extension;
                String addingDetails = "Added by: " + addedby + " " + dateAdded + " @ " + timeAdded;

                // Corrected: Display image
                if (imgBytes != null) {
                    displayImage(imgBytes,imageLabel);
                } else {
                    System.out.println("No image found for student ID: " + studID);
                }

                ID.setText(studID);
                studName.setText(fullName);
                studentEmail.setText(email);
                studMobNo.setText(mobileNo);
                addedBy.setText(addingDetails);
                yrlvl.setText(yrLevel);

                // Save QR code image
                // Assuming qr is a byte array column, you can directly save it as an image file
              qrBytes = resultSet.getBytes("qr");
            }
        }
    } catch (SQLException e) {
        String error = e.getMessage();
        JOptionPane.showMessageDialog(null, error);
    }
}

public void displayImage(byte[] img, JLabel imageLabel) {
    if (img == null || img.length == 0) {
        System.out.println("Error: Image data is null or empty");
        return;
    }
    
    try {
        ImageIcon imageIcon = new ImageIcon(img);
        Image image = imageIcon.getImage();
        Image scaledImage = image.getScaledInstance(300, 300, Image.SCALE_SMOOTH);
        ImageIcon scaledImageIcon = new ImageIcon(scaledImage);
        imageLabel.setIcon(scaledImageIcon);
    } catch (IllegalArgumentException | NullPointerException e) {
        System.out.println("Error displaying image: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLayeredPane1 = new javax.swing.JLayeredPane();
        infoPanel = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        studName = new javax.swing.JLabel();
        studentEmail = new javax.swing.JLabel();
        studMobNo = new javax.swing.JLabel();
        addedBy = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        yrlvl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        showQR = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        infoPanel.setBackground(new java.awt.Color(51, 153, 255));
        infoPanel.setForeground(new java.awt.Color(51, 204, 255));

        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        ID.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        ID.setForeground(new java.awt.Color(0, 0, 0));
        ID.setText("Student ID:");

        jLabel4.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Name:");

        jLabel5.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Email:");

        jLabel7.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Mobile No.:");

        jLabel8.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Student ID:");

        studName.setBackground(new java.awt.Color(102, 204, 255));
        studName.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        studName.setForeground(new java.awt.Color(0, 0, 0));
        studName.setText("Name");

        studentEmail.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        studentEmail.setForeground(new java.awt.Color(0, 0, 0));
        studentEmail.setText("Email");

        studMobNo.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        studMobNo.setForeground(new java.awt.Color(0, 0, 0));
        studMobNo.setText("Mobile No");

        addedBy.setFont(new java.awt.Font("Courier New", 1, 12)); // NOI18N
        addedBy.setForeground(new java.awt.Color(0, 0, 0));
        addedBy.setText("Added by:");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("BACK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        yrlvl.setBackground(new java.awt.Color(102, 204, 255));
        yrlvl.setFont(new java.awt.Font("Courier New", 1, 18)); // NOI18N
        yrlvl.setForeground(new java.awt.Color(0, 0, 0));
        yrlvl.setText("Year Level");

        jLabel9.setFont(new java.awt.Font("Courier New", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Year Level:");

        jLabel1.setFont(new java.awt.Font("Ebrima", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-identity-100.png"))); // NOI18N
        jLabel1.setText("Student Information");

        showQR.setText("SHOW QR");
        showQR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showQRActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout infoPanelLayout = new javax.swing.GroupLayout(infoPanel);
        infoPanel.setLayout(infoPanelLayout);
        infoPanelLayout.setHorizontalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addContainerGap(232, Short.MAX_VALUE)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(280, Short.MAX_VALUE))
            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, infoPanelLayout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(infoPanelLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(addedBy, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(showQR, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(infoPanelLayout.createSequentialGroup()
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(infoPanelLayout.createSequentialGroup()
                                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel7)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel8))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(studName, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studentEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(studMobNo, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yrlvl, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ID, javax.swing.GroupLayout.PREFERRED_SIZE, 468, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(infoPanelLayout.createSequentialGroup()
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(20, 20, 20)))
                    .addContainerGap()))
        );
        infoPanelLayout.setVerticalGroup(
            infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(infoPanelLayout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(369, Short.MAX_VALUE))
            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(infoPanelLayout.createSequentialGroup()
                    .addGap(25, 25, 25)
                    .addComponent(jLabel1)
                    .addGap(346, 346, 346)
                    .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(infoPanelLayout.createSequentialGroup()
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(ID))
                            .addGap(18, 18, 18)
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(studName))
                            .addGap(18, 18, 18)
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(yrlvl))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(studentEmail))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(infoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(studMobNo))
                            .addGap(50, 50, 50)
                            .addComponent(addedBy))
                        .addComponent(showQR, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(57, Short.MAX_VALUE)))
        );

        jLayeredPane1.setLayer(infoPanel, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(infoPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void showQRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showQRActionPerformed
        // TODO add your handling code here:
        //   saveQRCode(qrBytes,studID,200,200);
        String imgpath_name = "C:\\Downloads\\CompesaEventHandler\\CompesaAutomatedEventsHandler\\img\\img" ;

        // Only save the image if a new image has been selected

        saveDisplayedImageToFile(imgpath_name, studID);
        JOptionPane.showMessageDialog(this, "Qr Code Save Successfully to C:\\Downloads\\CompesaEventHandler\\CompesaAutomatedEventsHandler\\img\\img ");
    }//GEN-LAST:event_showQRActionPerformed
private void saveDisplayedImageToFile(String saveDirectory, String fileName) {
   try {
        File directory = new File(saveDirectory);
        if (!directory.exists()) {
            directory.mkdirs();
        }

        // Convert byte array to InputStream
        InputStream inputStream = new ByteArrayInputStream(qrBytes);

        // Read bytes from InputStream and create an image
        BufferedImage originalImage = ImageIO.read(inputStream);

        // Close the InputStream
        inputStream.close();

        // Ensure the directory exists
        if (!directory.exists()) {
            directory.mkdirs();
        }

        // Resize the image to 720x720 pixels
        Image scaledImage = originalImage.getScaledInstance(1080, 1080, Image.SCALE_SMOOTH);
        BufferedImage resizedImage = new BufferedImage(1080, 1080, BufferedImage.TYPE_INT_RGB);
        resizedImage.getGraphics().drawImage(scaledImage, 0, 0, null);

        // Construct the full path to save the image
        String savePath = Paths.get(saveDirectory, fileName + ".jpg").toString(); // Add ".jpg" extension

        // Write the resized image to the file
        File outputFile = new File(savePath);
        ImageIO.write(resizedImage, "jpg", outputFile);

        System.out.println("Image saved to: " + savePath);
    } catch (IOException ex) {
        Logger.getLogger(view.class.getName()).log(Level.SEVERE, null, ex);
    }
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ID;
    private javax.swing.JLabel addedBy;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel infoPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton showQR;
    private javax.swing.JLabel studMobNo;
    private javax.swing.JLabel studName;
    private javax.swing.JLabel studentEmail;
    private javax.swing.JLabel yrlvl;
    // End of variables declaration//GEN-END:variables
}
