/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package update;

import static dbcon.StudentDao.updateStud;
import static dbcon.StudentDao.updateStudent;
import formatting.inputFormatting;

import static initializer.displayOps.displayImageByteSource;
import static initializer.displayOps.displayImageStringSource;
import initializer.studentSettersAndGetters;
import static initializer.validators.validateInputs;
import java.awt.Image;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import net.glxn.qrgen.QRCode;
import net.glxn.qrgen.image.ImageType;
import tablesForm.JpanelLoader;
import tablesForm.studentsList;

/**
 *
 * @author User
 */
public class updateStud extends javax.swing.JPanel {

    /**
     * Creates new form addStudent
     */
    String qrpath;
    String addedBy;
    String imgname, oldStudentID, newStudentiD;
    String oldFirstName, oldMiddleName, oldLastName, oldExtension, email, mobileNo, addedby, dateAdded, timeAdded, oldRfid, yrLevel;
    String savepath1 = "C:\\Documents\\CompesaEventHandler\\CompesaAutomatedEventsHandler\\img\\img\\cpelogo.png";
    byte[] imageData;
    byte[] qrBytes;

    public updateStud(String studentID) {

        initComponents();
        this.addedBy = addedBy;
        this.oldStudentID = studentID;

        studentSettersAndGetters initializeStudent = new studentSettersAndGetters(studentID);
        imageData= initializeStudent.getImageData();
        oldFirstName = initializeStudent.getFirstName();
        oldMiddleName = initializeStudent.getMiddleName();
        oldLastName = initializeStudent.getLastName();
        oldExtension = initializeStudent.getExtension();
        email = initializeStudent.getEmail();
        mobileNo = initializeStudent.getMobileNo();
        IDField.setText(oldStudentID);
        oldRfid=initializeStudent.getRfid();
        yrLevel=initializeStudent.getYrLevel();
        
        firstNameField.setText(oldFirstName);
        middleNameField.setText(oldMiddleName);
        lastNameField.setText(oldLastName);
        extensionField.setText(oldExtension);
        emailField.setText(email);
        mobileNoField.setText(mobileNo);
        RFIDField.setText(oldRfid);
        yrLvlField.setText(yrLevel);

        displayImageByteSource(imageData, imageLabel);
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        IDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        middleNameField = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        clearButtons = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        extensionField = new javax.swing.JTextField();
        emailField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        extensionBox = new javax.swing.JComboBox<>();
        mobileNoField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        RFIDField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        addImageButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        yrLvlField = new javax.swing.JTextField();
        yrLvlBox = new javax.swing.JComboBox<>();
        openCamButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-50.png"))); // NOI18N
        jLabel1.setText("Update Student");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Student ID:");

        IDField.setBackground(new java.awt.Color(255, 255, 255));
        IDField.setForeground(new java.awt.Color(0, 0, 0));
        IDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("First Name:");

        firstNameField.setBackground(new java.awt.Color(255, 255, 255));
        firstNameField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Middle Name:");

        middleNameField.setBackground(new java.awt.Color(255, 255, 255));
        middleNameField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Last Name:");

        lastNameField.setBackground(new java.awt.Color(255, 255, 255));
        lastNameField.setForeground(new java.awt.Color(0, 0, 0));

        backButton.setBackground(new java.awt.Color(0, 204, 204));
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addStudentButton.setBackground(new java.awt.Color(153, 255, 0));
        addStudentButton.setForeground(new java.awt.Color(0, 0, 0));
        addStudentButton.setText("UPDATE STUDENT");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        clearButtons.setBackground(new java.awt.Color(255, 0, 51));
        clearButtons.setForeground(new java.awt.Color(0, 0, 0));
        clearButtons.setText("CLEAR INPUTS");
        clearButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Extension:");

        extensionField.setBackground(new java.awt.Color(255, 255, 255));
        extensionField.setForeground(new java.awt.Color(0, 0, 0));

        emailField.setBackground(new java.awt.Color(255, 255, 255));
        emailField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email:");

        extensionBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "None","Jr.", "Sr.", "I", "II","III","IV","V" }));
        extensionBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                extensionBoxActionPerformed(evt);
            }
        });

        mobileNoField.setBackground(new java.awt.Color(255, 255, 255));
        mobileNoField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mobile No.:");

        RFIDField.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("RFID:");

        imageLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageLabel.setText("      Choose image");
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        addImageButton.setBackground(new java.awt.Color(255, 102, 102));
        addImageButton.setText("Add Image");
        addImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Year Level:");

        yrLvlField.setBackground(new java.awt.Color(255, 255, 255));
        yrLvlField.setForeground(new java.awt.Color(0, 0, 0));

        yrLvlBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1st Year", "2nd Year","3rd Year","4th Year","Graduated","Shifted" }));
        yrLvlBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yrLvlBoxActionPerformed(evt);
            }
        });

        openCamButton.setBackground(new java.awt.Color(255, 102, 102));
        openCamButton.setText("Capture Image");
        openCamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openCamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addImageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel10)
                                        .addComponent(jLabel6))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(RFIDField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(13, 13, 13)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(extensionField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel11)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(yrLvlField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(mobileNoField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(extensionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(yrLvlBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap(424, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(addStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(clearButtons, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                .addComponent(backButton, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))))
                    .addContainerGap(19, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addImageButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(openCamButton)
                .addContainerGap(321, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(94, 94, 94)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel10)
                        .addComponent(RFIDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(20, 20, 20)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(IDField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(firstNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(middleNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lastNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(extensionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(extensionBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(yrLvlField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(yrLvlBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(emailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addGap(18, 18, 18)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel9)
                        .addComponent(mobileNoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(27, 27, 27)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(clearButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        extensionField.setEditable(false);
        yrLvlField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openCamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openCamButtonActionPerformed

    private void yrLvlBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yrLvlBoxActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) yrLvlBox.getSelectedItem();

        yrLvlField.setText(selectedItem);
    }//GEN-LAST:event_yrLvlBoxActionPerformed

    private void addImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageButtonActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getName();
            imgname = fileName;
            displayImageStringSource(selectedFile.getAbsolutePath(),imageLabel);
            try {
                imageData = Files.readAllBytes(selectedFile.toPath());
            } catch (IOException ex) {
                System.out.println(ex);
           
            }
        }
    }//GEN-LAST:event_addImageButtonActionPerformed

    private void extensionBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_extensionBoxActionPerformed
        // TODO add your handling code here:
        String selectedItem = (String) extensionBox.getSelectedItem();

        if (selectedItem.equalsIgnoreCase("None")) {
            extensionField.setText("");
        } else {

            extensionField.setText(selectedItem);
        }

    }//GEN-LAST:event_extensionBoxActionPerformed

    private void clearButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonsActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonsActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        String newStudentID = IDField.getText();
        String newFirstName = firstNameField.getText();
        String newMiddleName = middleNameField.getText();
        String newLastName = lastNameField.getText();
        String newExtension = extensionField.getText();
        String newEmail = emailField.getText();
        String newMobileNo = mobileNoField.getText();
        String newRfid = RFIDField.getText();
        String newYrLvl = yrLvlField.getText();
        Date currentDate = new Date();

        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        SimpleDateFormat timeFormat = new SimpleDateFormat("HH:mm");
        String dateAdded = dateFormat.format(currentDate);
        String timeAdded = timeFormat.format(currentDate);
    inputFormatting nameFormat = new inputFormatting();
       newFirstName = nameFormat.capitalizeWords(newFirstName);
        System.out.println(newFirstName);
       newLastName = nameFormat.capitalizeWords(newLastName);
               newMiddleName="";
        if (!newMiddleName.isEmpty()) {
   newMiddleName = nameFormat.capitalizeWords(newMiddleName);
        }
     
        if(validateInputs(newStudentID, newFirstName, newMiddleName, newLastName, newEmail, newMobileNo, imageData,this)){
              try {

                ByteArrayOutputStream out = QRCode.from(IDField.getText())
                        .to(ImageType.PNG).stream();
                qrBytes = out.toByteArray();

                String f_name = IDField.getText();
                String Path_name = "C:\\Documents\\CompesaEventHandler2.0\\CompesaAutomatedEventsHandler2.0\\qrcode\\qrcode";

                Path path = Paths.get(Path_name);

                if (!Files.exists(path)) {
                    try {
                        Files.createDirectories(path);
                        System.out.println("Folder created successfully!");
                    } catch (IOException e) {
                        System.err.println("Error creating folder: " + e.getMessage());
                    }
                }

                FileOutputStream fout = new FileOutputStream(new File(Path_name + (f_name + ".PNG")));
                qrpath = Path_name + "\\" + f_name + ".PNG"; // Construct the full image file path

                fout.write(out.toByteArray());
                fout.flush();

            } catch (Exception e) {
                System.out.println(e);
            }
//updateStud(String oldStudentID, String newStudentID, String firstName, String middleName, String lastName, String extension, String email, String mobileNo, byte[] qr, String addedBy, String dateAdded, String timeAdded, String rfid, byte[] img, String yrLvl)
            String rowsAffected = updateStud(oldStudentID, newStudentID, oldFirstName,newFirstName,oldMiddleName, newMiddleName, oldLastName,newLastName, oldExtension,newExtension,newEmail, newMobileNo, qrBytes, oldRfid, newRfid, imageData, newYrLvl);
            System.out.println(rowsAffected);
           if (rowsAffected.equals("Student Updated Successfully!")) {
            JOptionPane.showMessageDialog(updateStud.this, rowsAffected);
                    studentsList cus = new studentsList(addedBy);
        jpload.jPanelLoader(this, cus);
        } else {
            JOptionPane.showMessageDialog(updateStud.this,rowsAffected, "Error", JOptionPane.ERROR_MESSAGE);
        }
        }
    }//GEN-LAST:event_addStudentButtonActionPerformed
    JpanelLoader jpload = new JpanelLoader();

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        studentsList cus = new studentsList(addedBy);
        jpload.jPanelLoader(this, cus);

    }//GEN-LAST:event_backButtonActionPerformed

    private void IDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDFieldActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_IDFieldActionPerformed



    private void clear() {
        RFIDField.setText("");
        IDField.setText("");
        firstNameField.setText("");
        middleNameField.setText("");
        lastNameField.setText("");
        extensionField.setText("");
        yrLvlField.setText("");
        emailField.setText("");
        mobileNoField.setText("");
        extensionBox.setSelectedItem("None");
        extensionBox.setSelectedItem(" ");
        imageLabel.setIcon(null);
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField IDField;
    private javax.swing.JTextField RFIDField;
    private javax.swing.JButton addImageButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButtons;
    private javax.swing.JTextField emailField;
    private javax.swing.JComboBox<String> extensionBox;
    private javax.swing.JTextField extensionField;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField middleNameField;
    private javax.swing.JTextField mobileNoField;
    private javax.swing.JButton openCamButton;
    private javax.swing.JComboBox<String> yrLvlBox;
    private javax.swing.JTextField yrLvlField;
    // End of variables declaration//GEN-END:variables
}
