/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package update;

import add.*;
import com.formdev.flatlaf.FlatLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.fonts.roboto.FlatRobotoFont;
import com.raven.datechooser.DateChooser;
import com.raven.datechooser.EventDateChooser;
import com.raven.datechooser.SelectedAction;
import com.raven.datechooser.SelectedDate;
import com.raven.swing.TimePicker;
import static dbcon.eventDao.save;
import static dbcon.eventDao.updateEvents;
import initializer.EventGettersAndSetters;
import static initializer.displayOps.displayImageByteSource;
import static initializer.displayOps.displayImageStringSource;
import static initializer.displayOps.getImage;
import static initializer.validators.dateValidator;
import static initializer.validators.timeValidator;
import static initializer.validators.validFinesFormat;
import static initializer.validators.validateEventInputs;
import java.awt.Color;
import java.awt.Font;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import tablesForm.JpanelLoader;
import tablesForm.eventList;
import tablesForm.studentsList;

/**
 *
 * @author User
 */
public class updateEvent extends javax.swing.JPanel {

    /**
     * Creates new form addStudent
     */
    List<Object> selectedParticipants = new ArrayList<>();
    String qrpath;
    String addedBy;
    String imgname;
    String savepath1 = "C:\\Documents\\CompesaEventHandler\\CompesaAutomatedEventsHandler\\img\\img\\cpelogo.png";
    byte[] imageData, qrCodeImageData;
    
    
    int eventID;
String eventCode;
String eventName;
String eventDate;
String morningIn;
String morningOut;
String noonIn;
String noonOut;
String nightIn;
String nightOut;
String attendees;
String fines;
    DateChooser dateChooser = new DateChooser();
    public updateEvent(String username,String eventCode) {

        initComponents();
        FlatRobotoFont.install();
        FlatLaf.registerCustomDefaultsSource("multiSelectComboBox");
        UIManager.put("defaultFont", new Font(FlatRobotoFont.FAMILY, Font.PLAIN, 13));
        FlatLightLaf.setup();
        initComponents();
        EventGettersAndSetters fetchEvents=new EventGettersAndSetters(eventCode);
        
 this.eventID = fetchEvents.getEventID();
this.eventCode = fetchEvents.getEventCode();
this.eventName = fetchEvents.getEventName();
this.eventDate = fetchEvents.getEventDate();
this.morningIn = fetchEvents.getMorningIn();
this.morningOut = fetchEvents.getMorningOut();
this.noonIn = fetchEvents.getNoonIn();
this.noonOut = fetchEvents.getNoonOut();
this.nightIn = fetchEvents.getNightIn();
this.nightOut = fetchEvents.getNightOut();
this.attendees = fetchEvents.getParticipants();
this.imageData = fetchEvents.getEventPoster();
this.fines = fetchEvents.getFines();



eventCodeField.setText(eventCode);
eventNameField.setText(eventName);
eventDateField.setText(eventDate);
morningInField.setText(morningIn);
morningOutField.setText(morningOut);
noonInField.setText(noonIn);
noonOutField.setText(noonOut);
nightInField.setText(nightIn);
nightOutField.setText(nightOut);

 displayImageByteSource(imageData, imageLabel);
finesField.setText(fines);


        
        testData(participants);

    
   
        this.addedBy = addedBy;
      String[] resultArray = attendees.split(",\\s*");  // Splitting by comma and optional whitespace

        // Print out each element of the array
        for (String element : resultArray) {
            
          selectedParticipants.add(element);
        }
      participants.setSelectedItems(selectedParticipants);
        
        dateChooser.setTextReference(eventDateField);
        dateChooser.addEventDateChooser(new EventDateChooser() {
            @Override
            public void dateSelected(SelectedAction action, SelectedDate date) {
                System.out.println(date.getDay() + "-" + date.getMonth() + "-" + date.getYear());
                if (action.getAction() == SelectedAction.DAY_SELECTED) {
                    dateChooser.hidePopup();
                }
            }
        });
    }

    private void testData(JComboBox combo) {
        combo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{
            "1st Year",
            "2nd Year",
            "3rd Year",
            "4th Year",}));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        eventCodeField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        eventNameField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        finesField = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        addStudentButton = new javax.swing.JButton();
        clearButtons = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();
        addImageButton = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        openCamButton = new javax.swing.JButton();
        morningInField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        morningOutField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        noonInField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        noonOutField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        nightInField = new javax.swing.JTextField();
        nightOutField = new javax.swing.JTextField();
        eventDateField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        participants = new multiSelectComboBox.ComboBoxMultiSelection();
        clearMIN = new javax.swing.JButton();
        clearMIN1 = new javax.swing.JButton();
        clearMIN2 = new javax.swing.JButton();
        clearMIN3 = new javax.swing.JButton();
        clearMIN4 = new javax.swing.JButton();
        clearMIN5 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));

        jPanel1.setBackground(new java.awt.Color(0, 153, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.darkGray, java.awt.Color.gray));

        jLabel1.setFont(new java.awt.Font("Gill Sans MT", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8-update-50.png"))); // NOI18N
        jLabel1.setText("Update Event");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Event Code:");

        eventCodeField.setBackground(new java.awt.Color(255, 255, 255));
        eventCodeField.setForeground(new java.awt.Color(0, 0, 0));
        eventCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventCodeFieldActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Event Name:");

        eventNameField.setBackground(new java.awt.Color(255, 255, 255));
        eventNameField.setForeground(new java.awt.Color(0, 0, 0));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fines:");

        finesField.setBackground(new java.awt.Color(255, 255, 255));
        finesField.setForeground(new java.awt.Color(0, 0, 0));

        backButton.setBackground(new java.awt.Color(0, 204, 204));
        backButton.setForeground(new java.awt.Color(0, 0, 0));
        backButton.setText("BACK");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        addStudentButton.setBackground(new java.awt.Color(153, 255, 0));
        addStudentButton.setForeground(new java.awt.Color(0, 0, 0));
        addStudentButton.setText("UPDATE");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        clearButtons.setBackground(new java.awt.Color(255, 0, 51));
        clearButtons.setForeground(new java.awt.Color(0, 0, 0));
        clearButtons.setText("CLEAR INPUTS");
        clearButtons.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonsActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Morning In:");

        imageLabel.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        imageLabel.setForeground(new java.awt.Color(255, 255, 255));
        imageLabel.setText("      Choose image");
        imageLabel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        addImageButton.setBackground(new java.awt.Color(255, 102, 102));
        addImageButton.setText("Add Image");
        addImageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addImageButtonActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Participants:");

        openCamButton.setBackground(new java.awt.Color(255, 102, 102));
        openCamButton.setText("Capture Image");
        openCamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openCamButtonActionPerformed(evt);
            }
        });

        morningInField.setEditable(false);
        morningInField.setBackground(new java.awt.Color(255, 255, 255));
        morningInField.setForeground(new java.awt.Color(0, 0, 0));
        morningInField.setEnabled(false);
        morningInField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                morningInFieldMouseClicked(evt);
            }
        });
        morningInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morningInFieldActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Event Date :");

        jLabel9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Morning Out:");

        morningOutField.setEditable(false);
        morningOutField.setBackground(new java.awt.Color(255, 255, 255));
        morningOutField.setForeground(new java.awt.Color(0, 0, 0));
        morningOutField.setEnabled(false);
        morningOutField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                morningOutFieldMouseClicked(evt);
            }
        });
        morningOutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                morningOutFieldActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Noon In:");

        noonInField.setEditable(false);
        noonInField.setBackground(new java.awt.Color(255, 255, 255));
        noonInField.setForeground(new java.awt.Color(0, 0, 0));
        noonInField.setEnabled(false);
        noonInField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noonInFieldMouseClicked(evt);
            }
        });
        noonInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noonInFieldActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Noon Out:");

        noonOutField.setEditable(false);
        noonOutField.setBackground(new java.awt.Color(255, 255, 255));
        noonOutField.setForeground(new java.awt.Color(0, 0, 0));
        noonOutField.setEnabled(false);
        noonOutField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                noonOutFieldMouseClicked(evt);
            }
        });
        noonOutField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noonOutFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Night In:");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Night Out:");

        nightInField.setEditable(false);
        nightInField.setBackground(new java.awt.Color(255, 255, 255));
        nightInField.setForeground(new java.awt.Color(0, 0, 0));
        nightInField.setEnabled(false);
        nightInField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nightInFieldMouseClicked(evt);
            }
        });
        nightInField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nightInFieldActionPerformed(evt);
            }
        });

        nightOutField.setEditable(false);
        nightOutField.setBackground(new java.awt.Color(255, 255, 255));
        nightOutField.setForeground(new java.awt.Color(0, 0, 0));
        nightOutField.setEnabled(false);
        nightOutField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nightOutFieldMouseClicked(evt);
            }
        });

        eventDateField.setEditable(false);
        eventDateField.setBackground(new java.awt.Color(255, 255, 255));
        eventDateField.setForeground(new java.awt.Color(0, 0, 0));
        eventDateField.setDoubleBuffered(true);
        eventDateField.setDragEnabled(true);
        eventDateField.setEnabled(false);
        eventDateField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventDateFieldActionPerformed(evt);
            }
        });

        jButton1.setText("Date");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        participants.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                participantsActionPerformed(evt);
            }
        });

        clearMIN.setText("Clear");
        clearMIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMINActionPerformed(evt);
            }
        });

        clearMIN1.setText("Clear");
        clearMIN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMIN1ActionPerformed(evt);
            }
        });

        clearMIN2.setText("Clear");
        clearMIN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMIN2ActionPerformed(evt);
            }
        });

        clearMIN3.setText("Clear");
        clearMIN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMIN3ActionPerformed(evt);
            }
        });

        clearMIN4.setText("Clear");
        clearMIN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMIN4ActionPerformed(evt);
            }
        });

        clearMIN5.setText("Clear");
        clearMIN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearMIN5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(eventDateField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(morningInField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clearMIN))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(morningOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearMIN1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(noonInField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearMIN2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(noonOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearMIN3))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nightInField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearMIN4))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nightOutField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(clearMIN5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(finesField, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE)
                            .addComponent(participants, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imageLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(openCamButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addImageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(backButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearButtons, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(106, 106, 106)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(eventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(eventCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(302, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(jLabel1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(eventDateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(addImageButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(openCamButton))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(morningInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(clearMIN))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(morningOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(clearMIN1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(noonInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearMIN2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(noonOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearMIN3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nightInField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearMIN4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nightOutField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearMIN5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(participants, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(finesField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(clearButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(138, 138, 138)
                    .addComponent(eventCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(18, 18, 18)
                    .addComponent(eventNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(419, Short.MAX_VALUE)))
        );

        eventDateField.setEditable(false);
        eventDateField.setEditable(false);
        eventDateField.setEditable(false);
        eventDateField.setEditable(false);
        eventDateField.setEditable(false);
        eventDateField.setEditable(false);
        eventDateField.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void openCamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openCamButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openCamButtonActionPerformed

    private void addImageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addImageButtonActionPerformed
        // TODO add your handling code here:

        JFileChooser fileChooser = new JFileChooser();
        int result = fileChooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            String fileName = selectedFile.getName();
            imgname = fileName;
            displayImageStringSource(selectedFile.getAbsolutePath(), imageLabel);
            try {
                imageData = Files.readAllBytes(selectedFile.toPath());
            } catch (IOException ex) {
                //Logger.getLogger(addStudent.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_addImageButtonActionPerformed

    private void clearButtonsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonsActionPerformed
        clear();
    }//GEN-LAST:event_clearButtonsActionPerformed
String errorMessage = "";
    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
            errorMessage="";
    String eCode = eventCodeField.getText();
    String eName = eventNameField.getText();
    String eDate = eventDateField.getText();
    String mIn = morningInField.getText();
    String mOut = morningOutField.getText();
    String aIn = noonInField.getText();
    String aOut = noonOutField.getText();
    String nIn = nightInField.getText();
    String nOut = nightOutField.getText();
    // String participants= participantsField.getText();
    selectedParticipants = participants.getSelectedItems();

    String participant = new StringBuilder()
            .append(selectedParticipants.stream()
                    .map(Object::toString)
                    .collect(Collectors.joining(", ")))
            .toString();

    String stringFines = finesField.getText();
    mIn = timeValidator(mIn);
    mOut = timeValidator(mOut);
    aIn = timeValidator(aIn);
    aOut = timeValidator(aOut);
    nIn = timeValidator(nIn);
    nOut = timeValidator(nOut);
    
    errorMessage += validateEventInputs(eCode, eName, eDate, mIn, mOut, aIn, aOut, nIn, nOut, participant, imageData, stringFines);
    
    if (errorMessage.isEmpty()) {
        errorMessage = "";
        errorMessage += dateValidator(eDate, mIn, mOut, aIn, aOut, nIn, nOut);

        if (!validFinesFormat(stringFines)) {
            errorMessage += "Invalid fines format. Fines must be between 0 to 999";
            JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
        }

        if (errorMessage.isEmpty()) {
      
               int success = updateEvents(eventID, eCode, eName, eDate, mIn, mOut, aIn, aOut, nIn, nOut, participant, imageData, stringFines);;
            if (success == 1) {
                JOptionPane.showMessageDialog(null, "Updated Successfully", "Success", JOptionPane.INFORMATION_MESSAGE);
                eventList cus = new eventList(addedBy);
                jpload.jPanelLoader(this, cus);
            }
        } else {
            JOptionPane.showMessageDialog(null,  errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
            errorMessage="";
        }
    } else {
        JOptionPane.showMessageDialog(null, errorMessage, "Error", JOptionPane.ERROR_MESSAGE);
        errorMessage="";
    }
        /*String[] resultArray = result.split(",\\s*");  // Splitting by comma and optional whitespace

        // Print out each element of the array
        for (String element : resultArray) {
            System.out.println(element);
        }
        System.out.println(result); */
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
       eventList cus = new eventList(addedBy);
        jpload.jPanelLoader(this, cus);
    }//GEN-LAST:event_backButtonActionPerformed

    private void eventCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventCodeFieldActionPerformed

    }//GEN-LAST:event_eventCodeFieldActionPerformed

    private void morningInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morningInFieldActionPerformed

    }//GEN-LAST:event_morningInFieldActionPerformed

    private void morningOutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_morningOutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_morningOutFieldActionPerformed

    private void noonInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noonInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noonInFieldActionPerformed

    private void noonOutFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noonOutFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noonOutFieldActionPerformed

    private void nightInFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nightInFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nightInFieldActionPerformed

    private void morningInFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_morningInFieldMouseClicked
        // TODO add your handling code here:
        TimePicker timePicker1 = new TimePicker();
        timePicker1.showPopup(this, (getWidth() - timePicker1.getPreferredSize().width) / 2, (getHeight() - timePicker1.getPreferredSize().height) / 2);

        timePicker1.setForeground(new java.awt.Color(50, 128, 255));
        timePicker1.setDisplayText(morningInField);
    }//GEN-LAST:event_morningInFieldMouseClicked

    private void morningOutFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_morningOutFieldMouseClicked
        // TODO add your handling code here:
        TimePicker timePicker1 = new TimePicker();
        timePicker1.showPopup(this, (getWidth() - timePicker1.getPreferredSize().width) / 2, (getHeight() - timePicker1.getPreferredSize().height) / 2);
        timePicker1.setForeground(new java.awt.Color(50, 128, 255));
        timePicker1.setDisplayText(morningOutField);
    }//GEN-LAST:event_morningOutFieldMouseClicked

    private void noonInFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noonInFieldMouseClicked
        // TODO add your handling code here:
        TimePicker timePicker1 = new TimePicker();
        timePicker1.showPopup(this, (getWidth() - timePicker1.getPreferredSize().width) / 2, (getHeight() - timePicker1.getPreferredSize().height) / 2);
        timePicker1.setForeground(new java.awt.Color(50, 128, 255));
        timePicker1.setDisplayText(noonInField);
    }//GEN-LAST:event_noonInFieldMouseClicked

    private void noonOutFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_noonOutFieldMouseClicked
        // TODO add your handling code here:
        TimePicker timePicker1 = new TimePicker();
        timePicker1.showPopup(this, (getWidth() - timePicker1.getPreferredSize().width) / 2, (getHeight() - timePicker1.getPreferredSize().height) / 2);
        timePicker1.setForeground(new java.awt.Color(50, 128, 255));
        timePicker1.setDisplayText(noonOutField);
    }//GEN-LAST:event_noonOutFieldMouseClicked

    private void nightOutFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nightOutFieldMouseClicked
        // TODO add your handling code here:
        TimePicker timePicker1 = new TimePicker();
        timePicker1.showPopup(this, (getWidth() - timePicker1.getPreferredSize().width) / 2, (getHeight() - timePicker1.getPreferredSize().height) / 2);
        timePicker1.setForeground(new java.awt.Color(50, 128, 255));
        timePicker1.setDisplayText(nightOutField);
    }//GEN-LAST:event_nightOutFieldMouseClicked

    private void nightInFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nightInFieldMouseClicked
        // TODO add your handling code here:
        TimePicker timePicker1 = new TimePicker();
        timePicker1.showPopup(this, (getWidth() - timePicker1.getPreferredSize().width) / 2, (getHeight() - timePicker1.getPreferredSize().height) / 2);
        timePicker1.setForeground(new java.awt.Color(50, 128, 255));
        timePicker1.setDisplayText(nightInField);
    }//GEN-LAST:event_nightInFieldMouseClicked

    private void eventDateFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventDateFieldActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:

    }//GEN-LAST:event_eventDateFieldActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dateChooser.showPopup();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearMINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMINActionPerformed
        // TODO add your handling code here:
        morningInField.setText("");
    }//GEN-LAST:event_clearMINActionPerformed

    private void clearMIN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMIN1ActionPerformed
        // TODO add your handling code here:
        morningOutField.setText("");
    }//GEN-LAST:event_clearMIN1ActionPerformed

    private void clearMIN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMIN2ActionPerformed
        // TODO add your handling code here:
        noonInField.setText("");
    }//GEN-LAST:event_clearMIN2ActionPerformed

    private void clearMIN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMIN3ActionPerformed
        // TODO add your handling code here:
              noonOutField.setText("");
    }//GEN-LAST:event_clearMIN3ActionPerformed

    private void clearMIN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMIN4ActionPerformed
        // TODO add your handling code here:
        nightInField.setText("");
    }//GEN-LAST:event_clearMIN4ActionPerformed

    private void clearMIN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearMIN5ActionPerformed
        // TODO add your handling code here:
        nightOutField.setText("");
    }//GEN-LAST:event_clearMIN5ActionPerformed

    private void participantsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_participantsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_participantsActionPerformed
    JpanelLoader jpload = new JpanelLoader();

     private void clear() {
eventCodeField.setText("");
eventNameField.setText("");
eventDateField.setText("");
morningInField.setText("");
morningOutField.setText("");
noonInField.setText("");
noonOutField.setText("");
nightInField.setText("");
nightOutField.setText("");
  imageLabel.setIcon(null);
  finesField.setText("");
      selectedParticipants.clear();
        participants.setSelectedItems(selectedParticipants);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addImageButton;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton clearButtons;
    private javax.swing.JButton clearMIN;
    private javax.swing.JButton clearMIN1;
    private javax.swing.JButton clearMIN2;
    private javax.swing.JButton clearMIN3;
    private javax.swing.JButton clearMIN4;
    private javax.swing.JButton clearMIN5;
    private javax.swing.JTextField eventCodeField;
    private javax.swing.JTextField eventDateField;
    private javax.swing.JTextField eventNameField;
    private javax.swing.JTextField finesField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField morningInField;
    private javax.swing.JTextField morningOutField;
    private javax.swing.JTextField nightInField;
    private javax.swing.JTextField nightOutField;
    private javax.swing.JTextField noonInField;
    private javax.swing.JTextField noonOutField;
    private javax.swing.JButton openCamButton;
    private multiSelectComboBox.ComboBoxMultiSelection participants;
    // End of variables declaration//GEN-END:variables
}
